CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'media_app') THEN
		CREATE ROLE media_app LOGIN PASSWORD 'media_password';
	END IF;
END
$$;

ALTER DATABASE whispr_media OWNER TO media_app;
CREATE SCHEMA IF NOT EXISTS media AUTHORIZATION media_app;
GRANT ALL PRIVILEGES ON SCHEMA media TO media_app;
