name: 🏷️ Auto-Labeller

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-label:
    name: 🏷️ Label Pull Request
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: 🏷️ Apply Labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true

  priority-labeler:
    name: 🎯 Priority & Impact Assessment
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: auto-label

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Analyze PR Impact
        id: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAGER: ""
        run: |
          # Get changed files
          echo "Analyzing changed files..."

          # Critical files that require high priority - Media Service Specific
          CRITICAL_FILES="src/main.ts src/app.module.ts src/modules/media/media.module.ts src/modules/media/media.service.ts src/modules/storage/storage.service.ts prisma/schema.prisma docker/Dockerfile docker-compose.yml .github/workflows/"

          # Security-related files
          SECURITY_FILES="src/modules/auth/ src/modules/encryption/ src/common/guards/"

          # Media processing files
          MEDIA_FILES="src/modules/media/ src/modules/storage/"

          # Get PR files
          gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' > changed_files.txt

          # Initialize flags
          CRITICAL_CHANGED=false
          SECURITY_CHANGED=false
          DATABASE_CHANGED=false
          TESTS_CHANGED=false
          DOCS_CHANGED=false
          MEDIA_CHANGED=false
          STORAGE_CHANGED=false
          GRPC_CHANGED=false
          CACHE_CHANGED=false

          # Check each changed file
          while IFS= read -r file; do
            echo "Checking file: $file"

            # Check critical files
            for pattern in $CRITICAL_FILES; do
              if [[ "$file" == *"$pattern"* ]]; then
                echo "critical=true" >> $GITHUB_OUTPUT
                CRITICAL_CHANGED=true
                break
              fi
            done

            # Check security files
            for pattern in $SECURITY_FILES; do
              if [[ "$file" == *"$pattern"* ]]; then
                echo "security=true" >> $GITHUB_OUTPUT
                SECURITY_CHANGED=true
                break
              fi
            done

            # Check media processing
            if [[ "$file" == *"media"* ]] || [[ "$file" == *"ffmpeg"* ]] || [[ "$file" == *"sharp"* ]]; then
              echo "media=true" >> $GITHUB_OUTPUT
              MEDIA_CHANGED=true
            fi

            # Check storage
            if [[ "$file" == *"storage"* ]] || [[ "$file" == *"gcs"* ]]; then
              echo "storage=true" >> $GITHUB_OUTPUT
              STORAGE_CHANGED=true
            fi

            # Check gRPC
            if [[ "$file" == *"grpc"* ]] || [[ "$file" == *".proto"* ]]; then
              echo "grpc=true" >> $GITHUB_OUTPUT
              GRPC_CHANGED=true
            fi

            # Check cache/Redis
            if [[ "$file" == *"cache"* ]] || [[ "$file" == *"redis"* ]]; then
              echo "cache=true" >> $GITHUB_OUTPUT
              CACHE_CHANGED=true
            fi

            # Check database changes
            if [[ "$file" == *"migration"* ]] || [[ "$file" == *"prisma"* ]] || [[ "$file" == *"schema.prisma"* ]]; then
              echo "database=true" >> $GITHUB_OUTPUT
              DATABASE_CHANGED=true
            fi

            # Check test files
            if [[ "$file" == *".spec.ts"* ]] || [[ "$file" == *".test.ts"* ]] || [[ "$file" == *"test/"* ]]; then
              echo "tests=true" >> $GITHUB_OUTPUT
              TESTS_CHANGED=true
            fi

            # Check documentation
            if [[ "$file" == *".md"* ]] || [[ "$file" == *"documentation/"* ]]; then
              echo "docs=true" >> $GITHUB_OUTPUT
              DOCS_CHANGED=true
            fi

          done < changed_files.txt

          # Calculate PR size
          CHANGED_LINES=$(gh pr view ${{ github.event.pull_request.number }} --json additions,deletions --jq '.additions + .deletions')
          echo "changed_lines=$CHANGED_LINES" >> $GITHUB_OUTPUT

          if (( CHANGED_LINES > 1000 )); then
            echo "size=XL" >> $GITHUB_OUTPUT
          elif (( CHANGED_LINES > 500 )); then
            echo "size=L" >> $GITHUB_OUTPUT
          elif (( CHANGED_LINES > 100 )); then
            echo "size=M" >> $GITHUB_OUTPUT
          elif (( CHANGED_LINES > 10 )); then
            echo "size=S" >> $GITHUB_OUTPUT
          else
            echo "size=XS" >> $GITHUB_OUTPUT
          fi

      - name: 🎯 Apply Priority Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            const labels = [];

            // Priority labels based on impact
            if ('${{ steps.analyze.outputs.critical }}' === 'true') {
              labels.push('🔥 priority:high');
            } else if ('${{ steps.analyze.outputs.security }}' === 'true' || '${{ steps.analyze.outputs.database }}' === 'true') {
              labels.push('⚡ priority:medium');
            } else {
              labels.push('📝 priority:low');
            }

            // Size labels
            const size = '${{ steps.analyze.outputs.size }}';
            labels.push(`📏 size:${size}`);

            // Type-specific labels
            if ('${{ steps.analyze.outputs.tests }}' === 'true') {
              labels.push('🧪 type:testing');
            }

            if ('${{ steps.analyze.outputs.docs }}' === 'true') {
              labels.push('📚 type:documentation');
            }

            if ('${{ steps.analyze.outputs.security }}' === 'true') {
              labels.push('🔒 type:security');
            }

            if ('${{ steps.analyze.outputs.database }}' === 'true') {
              labels.push('🗄️ type:database');
            }

            // Media service specific labels
            if ('${{ steps.analyze.outputs.media }}' === 'true') {
              labels.push('🎥 media:video');
              labels.push('🖼️ media:image');
            }

            if ('${{ steps.analyze.outputs.storage }}' === 'true') {
              labels.push('☁️ storage:gcs');
            }

            if ('${{ steps.analyze.outputs.grpc }}' === 'true') {
              labels.push('📡 grpc');
            }

            if ('${{ steps.analyze.outputs.cache }}' === 'true') {
              labels.push('💾 cache:redis');
            }

            // Apply labels
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels
              });
            }
